# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cities_pb2 as cities__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cities_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CitiesGameStub(object):
    """Сервис CitiesGame
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/citiesgame.CitiesGame/StartGame',
                request_serializer=cities__pb2.StartGameRequest.SerializeToString,
                response_deserializer=cities__pb2.StartGameResponse.FromString,
                _registered_method=True)
        self.MakeMove = channel.unary_unary(
                '/citiesgame.CitiesGame/MakeMove',
                request_serializer=cities__pb2.MakeMoveRequest.SerializeToString,
                response_deserializer=cities__pb2.MakeMoveResponse.FromString,
                _registered_method=True)


class CitiesGameServicer(object):
    """Сервис CitiesGame
    """

    def StartGame(self, request, context):
        """Запуск новой игры
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeMove(self, request, context):
        """Сделать ход
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CitiesGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=cities__pb2.StartGameRequest.FromString,
                    response_serializer=cities__pb2.StartGameResponse.SerializeToString,
            ),
            'MakeMove': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeMove,
                    request_deserializer=cities__pb2.MakeMoveRequest.FromString,
                    response_serializer=cities__pb2.MakeMoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'citiesgame.CitiesGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('citiesgame.CitiesGame', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CitiesGame(object):
    """Сервис CitiesGame
    """

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/citiesgame.CitiesGame/StartGame',
            cities__pb2.StartGameRequest.SerializeToString,
            cities__pb2.StartGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/citiesgame.CitiesGame/MakeMove',
            cities__pb2.MakeMoveRequest.SerializeToString,
            cities__pb2.MakeMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
