# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cities.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ities.proto\x12\ncitiesgame\"\x12\n\x10StartGameRequest\"$\n\x11StartGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0fMakeMoveRequest\x12\x10\n\x08\x63ityName\x18\x01 \x01(\t\"c\n\x10MakeMoveResponse\x12\x13\n\x0bisValidMove\x18\x01 \x01(\x08\x12\x12\n\nnextLetter\x18\x02 \x01(\t\x12\x14\n\x0c\x65rrorMessage\x18\x03 \x01(\t\x12\x10\n\x08gameOver\x18\x04 \x01(\x08\x32\x9d\x01\n\nCitiesGame\x12H\n\tStartGame\x12\x1c.citiesgame.StartGameRequest\x1a\x1d.citiesgame.StartGameResponse\x12\x45\n\x08MakeMove\x12\x1b.citiesgame.MakeMoveRequest\x1a\x1c.citiesgame.MakeMoveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTGAMEREQUEST']._serialized_start=28
  _globals['_STARTGAMEREQUEST']._serialized_end=46
  _globals['_STARTGAMERESPONSE']._serialized_start=48
  _globals['_STARTGAMERESPONSE']._serialized_end=84
  _globals['_MAKEMOVEREQUEST']._serialized_start=86
  _globals['_MAKEMOVEREQUEST']._serialized_end=121
  _globals['_MAKEMOVERESPONSE']._serialized_start=123
  _globals['_MAKEMOVERESPONSE']._serialized_end=222
  _globals['_CITIESGAME']._serialized_start=225
  _globals['_CITIESGAME']._serialized_end=382
# @@protoc_insertion_point(module_scope)
